# Generated by Django 5.2.3 on 2025-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('sap_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primary_contact', models.CharField(max_length=20)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('focal_person', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
